modLoader="javafml"
loaderVersion="[1,)" # javafml version, not neoforge version

license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="${mod_id}"
version="${version}+${mc_ver}+${loader_name}"
displayName="${name}"
displayURL="${website}"
logoFile="${icon}"
authors="${authors}"
description='''${description}'''
# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

[[mixins]]
config="${mixins_file}"

[[dependencies.${mod_id}]]
modId="neoforge"
versionRange="${neoforge_range}"

[[dependencies.${mod_id}]]
modId="minecraft"
versionRange="${mc_range}"